### ISSUE TITLE
Wrong text color when using \FormulaVariable inside of \Attribute

### ISSUE THREAD

**Issue by skaldarnar** [potsdam-pnp/pf2e-cards#38]
The text under the `\FormulaVariable` box is supposed to be black (or the current text color), but when using it inside of an `\Attribute` the text is rendered in grey.

![image](https://github.com/potsdam-pnp/pf2e-cards/assets/1448874/bfd56e24-e145-4a2b-b17a-a3870ca4c669)

MWE to reproduce this (this also happens on the Bulk card):

```latex
\Card{}{}{Sandbox}

Attribute with plain text:

\Attribute{Foo}{black text}

Formula variable outside of Attribute:

\(\FormulaVariable{black text}{\phantom{1000}}\)

Formula variable inside of Attribute:

\Attribute{Bar}{%
  \(\FormulaVariable{grey text}{\phantom{1000}}\)
}

Text and Formula variable inside of Attribute:

\Attribute{Bar}{%
  make it black \(\FormulaVariable{grey text}{\phantom{1000}}\)
}
```

---

Observed on f92fdcc6b39e3554c963108f10c37072181969a4.

**Comment by Toxaris** [comment]
This is caused by ~tikz options being inherited by nested pictures~ \normalcolor being stupid, see https://comp.text.tex.narkive.com/c4Lci91f/bug-in-xcolor-normalcolor-does-not-change-internal-latex-macros-like-the-current-color
